name: Assassin
version: ${project.version}
main: cloud.lagrange.assassin.ManHuntPlugin
api-version: 1.13
authors: [NateKomodo]
description: A replica of the assassin game mode from Dream's video
commands:
  assassin:
    description: Sets player as assassin for the assassin game mode
    usage: <command> <player> [remove]
  speedrunner:
    description: Sets player as speedrunner for the assassin game mode
    usage: <command> <player> [remove]
  manhunt:
    description: Show current manhunt teams
    usage: <command>
